#!/usr/bin/env bash
_args=("$@")
for _idx in ${!_args[@]}
do
  if [[ ${_args[$_idx]} =~ [[:space:]\&] ]]
  then
    printf '"%s"' "${_args[$_idx]//\"/\\\"}"
  else
    printf '%s' ${_args[$_idx]}
  fi
  (( _idx == ${#_args[@]} - 1 )) || printf ' '
done
printf '\n'
