name: "Build"
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install Dependencies"
        run: |
          apt update
          apt install -y git
          git clone https://github.com/bats-core/bats-core.git
          bats-core/install.sh /usr/local
      - name: "Tests"
        run: bats test/ansible.bats test/tmp.bats
